on:
  push:
    branches: [main]
    paths:
      - 'packages/ponder/**'
      - '.github/workflows/workstation-development.yml'

jobs:
  deploy:
    runs-on: [self-hosted, raihanard]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate .env file
        working-directory: ./packages/ponder
        run: |
          touch .env
          grep -q '^DATABASE_URL=' .env && sed -i 's|^DATABASE_URL=.*|DATABASE_URL=${{ secrets.DATABASE_URL }}|' .env || echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          grep -q '^PONDER_RPC_URL_LISK=' .env && sed -i 's|^PONDER_RPC_URL_LISK=.*|PONDER_RPC_URL_LISK=${{ secrets.PONDER_RPC_URL_LISK }}|' .env || echo PONDER_RPC_URL_LISK=${{ secrets.PONDER_RPC_URL_LISK }} >> .env

      - name: Print .env contents (debug)
        working-directory: ./packages/ponder
        run: cat .env

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies (monorepo)
        run: bun install

      - name: Change directory to packages/ponder
        working-directory: ./packages/ponder
        run: echo "Changed to Ponder"

      - name: Start or Reload Ponder via PM2
        working-directory: ./packages/ponder
        run: pm2 restart ponder
